### ISSUE TITLE
Add GNU GTS flag for Graphviz/Homebrew in README?

### ISSUE THREAD

**Issue by terorie** [pahen/madge#170]
This isn't an issue with madge, just an idea for the README.

Sometimes installing Graphviz alone isn't enough to make everything work.
The **sfdp** layout seems to depend on GNU GTS.

Homebrew doesn't include GTS by default.
But it can be installed like this: `brew install graphviz --with-gts`.

Maybe it would be a good idea to add `--with-gts` in the README?

Here's what would happen without GTS, which could be confusing:
```
$ madge -i img.svg -l sfdp .
Processed 166 files (2.9s) 


✖ Error: Error: remove_overlap: Graphviz not built with triangulation library

    at g.output (/usr/local/lib/node_modules/madge/lib/graph.js:110:11)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/madge/node_modules/graphviz/lib/deps/graph.js:375:21)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

**Comment by pahen** [comment]
Added a note about this in the FAQ: https://github.com/pahen/madge#how-do-i-fix-the-graphviz-not-built-with-triangulation-library-error-when-using-sfdp-layout
