### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by techsin** [pahen/madge#177]
when i type madge in windows command line 

`madge app.js`

i get 

```
at commonJSLookup (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\filing-cabinet\index.js:208:14)
    at jsLookup (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\filing-cabinet\index.js:154:14)
    at cabinet (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\filing-cabinet\index.js:62:18)
    at Function.module.exports._getDependencies (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\dependency-tree\index.js:103:20)
    at traverse (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\dependency-tree\index.js:147:37)
    at traverse (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\dependency-tree\index.js:173:20)
    at traverse (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\dependency-tree\index.js:173:20)
    at traverse (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\dependency-tree\index.js:173:20)
    at traverse (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\dependency-tree\index.js:173:20)
    at traverse (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\dependency-tree\index.js:173:20)
```

**Comment by angelsvirkov** [comment]
Have you had a look at this one #157 ? If you have dynamic inline imports then that would be the problem.

**Comment by techsin** [comment]
im not doing any dynamic imports though

**Comment by mrjoelkemp** [comment]
Hey @techsin. Thanks for reporting the issue. Could you try a fresh install of madge and see if the problem persists? There was a bug fix to one of the dependencies pushed recently. I'm not sure that'll fix the issue since versions have to match, but figured it would be worth trying in the meantime.

**Comment by mrjoelkemp** [comment]
Woot. Glad to hear. https://github.com/dependents/node-detective-cjs/pull/9 was likely the fix. Enjoy!
