### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sudheerj** [pahen/madge#197]
As stated in the issue #177 , the above mentioned issue has been be fixed in the latest version. But when I tried with latest version as well as older version(3.1.0), I can still see the same issue.  Is the issue fixed in the latest release.

**Comment by pahen** [comment]
Can you provide more details please. What is the command you're running? Do you get any stacktrace with the error message?

**Comment by sudheerj** [comment]
Thank you for the response. I tried to run below madge commands,

`madge --circular src/modules
 madge --image graph.svg src/images
`
The stacktrace is same as #177 
`✖ TypeError: Cannot read property '0' of undefined
    at commonJSLookup (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\filing-cabinet\index.js:243:17)
    at jsLookup (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\filing-cabinet\index.js:177:14)
    at cabinet (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\filing-cabinet\index.js:75:18)
    at Function.module.exports._getDependencies (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\dependency-tree\index.js:104:20)
    at traverse (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\dependency-tree\index.js:149:37)
    at module.exports (C:\Users\username\AppData\Roaming\npm\node_modules\madge\node_modules\dependency-tree\index.js:35:19)
    at files.forEach (C:\Users\username\AppData\Roaming\npm\node_modules\madge\lib\tree.js:116:27)
    at Array.forEach (<anonymous>)
    at Tree.generateTree (C:\Users\username\AppData\Roaming\npm\node_modules\madge\lib\tree.js:111:9)
`
The main intention for the usage is to show both the detection warnings and visualization graph in Jenkins CI.

**Comment by pahen** [comment]
Do you know what file it breaks on? I'm interested in the content of that file.

**Comment by sudheerj** [comment]
I'am executing this command on entire modules folder

**Comment by pahen** [comment]
Can you try running madge with the `--debug` option and see if you can see what file it breaks on?

**Comment by sudheerj** [comment]
I observed that it fails with dynamic imports https://developers.google.com/web/updates/2017/11/dynamic-import

**Comment by sudheerj** [comment]
Sure. I will raise the bug in node-detective project. The dynamic import looks like this

`await localizedModule(app, 'modulename', locale => import(`modulename/locales/${locale}`));`

**Comment by mrjoelkemp** [comment]
Cool. Thanks for filing! The runtime error is likely a bug, but even with the fix, that import won't resolve to a file since it's evaluated at runtime (due to the interpolation).

I'll look into the runtime exception when I get a moment.

**Comment by mrjoelkemp** [comment]
I tried recreating it in node-filing cabinet with the dynamic import with interpolation and couldn't trigger the error. It wasn't a problem in the detective, as far as I could tell. 

Though I'm not entirely sure how an undefined partial was generated, I now handle the undefined partial instead of throwing a runtime exception. That fix is in a patch release. If you fresh install madge, you should get it. Let me know if you get the same issue; if you don't, then this bug can be closed.

If you could supply the `--debug` output, that could help me better understand what's going wrong.

**Comment by sudheerj** [comment]
Thanks @mrjoelkemp. It is working fine now. @pahen Do you have any guidelines for integrating SVG image in jenkins build

**Comment by pahen** [comment]
Thanks @mrjoelkemp! Nice that you got it working :) No, sorry @sudheerj
