### ISSUE TITLE
Using pify@5.0.0 on Made v3.9.0 killed Node v6 support

### ISSUE THREAD

**Issue by alayliercan** [pahen/madge#247]
[Changelog](https://github.com/pahen/madge/blob/master/CHANGELOG.md#v390-may-07-2020) doesn't state that you stopped supporting Node v6 starting with Madge v3.9.0.
However, usage of spread operator in pify v5 seems to have broken Node v6 support.
I wonder if this was this unintentional?

```bash
$ gulp build

/Users/redactedusername/Documents/redactedprojectname/node_modules/madge/node_modules/pify/index.js:44
		...options
		^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/redactedusername/Documents/redactedprojectname/node_modules/madge/lib/tree.js:5:14)
```

p.s.: I can build my typescript project with Madge v3.8.0 + Node v6 with no issues.

**Comment by pahen** [comment]
Yes, I have no plans for supporting Node 6
