### ISSUE TITLE
Update typescript version for v7

### ISSUE THREAD

**Issue by vldslv-a** [pahen/madge#410]
I get an error after installing madge v7:

⠋ Finding files=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.4.5

Please only submit bug reports when using the officially supported version.

=============

✖ TypeError: Cannot read properties of undefined (reading 'filter')
    at tsLookup (/usr/local/lib/node_modules/madge/node_modules/filing-cabinet/index.js:263:8)
    at module.exports (/usr/local/lib/node_modules/madge/node_modules/filing-cabinet/index.js:74:18)
    at module.exports._getDependencies (/usr/local/lib/node_modules/madge/node_modules/dependency-tree/index.js:100:20)
    at traverse (/usr/local/lib/node_modules/madge/node_modules/dependency-tree/index.js:146:37)
    at traverse (/usr/local/lib/node_modules/madge/node_modules/dependency-tree/index.js:170:29)
    at module.exports (/usr/local/lib/node_modules/madge/node_modules/dependency-tree/index.js:37:19)
    at /usr/local/lib/node_modules/madge/lib/tree.js:121:27
    at Array.forEach (<anonymous>)
    at Tree.generateTree (/usr/local/lib/node_modules/madge/lib/tree.js:116:9)

Could you please fix ts support in the near future?

**Comment by fdc-viktor-luft** [comment]
This was released now, which should fix that issue:

https://github.com/dependents/node-dependency-tree/releases/tag/v11.0.0

**Comment by vldslv-a** [comment]
It didn't solve my problem.

**Comment by fdc-viktor-luft** [comment]
@vldslv-a You have to wait for the next release, which will include this fix. But since there is nothing else to be done, this issue was closed by merging the PR.

**Comment by MBerka** [comment]
Note: this was not fixed in the NPM package. The last release there (8.0.0 in August 2024) has the peer dependency `"typescript": "^5.4.4"`. There is an [open issue on adding TS 6](https://github.com/pahen/madge/issues/462).
