### ISSUE TITLE
Get unsupported typescript version error on vue files even after downgrading to supported version range

### ISSUE THREAD

**Issue by Akindin** [pahen/madge#441]
npx tsc -v gives Version 5.5.4
tsc -v gives Version 5.5.4
npx vue-tsc -v gives Version 5.5.4

```
madge --extensions ts,vue --image graph.svg src/

⠋ Finding files=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.3

Please only submit bug reports when using the officially supported version.

=============

✖ SyntaxError: Unexpected token (7:2)
    at constructor (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:362:19)
    at FlowParserMixin.raise (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:3259:19)
    at FlowParserMixin.unexpected (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:3279:16)      
    at FlowParserMixin.parseExprAtom (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10970:16)  
    at FlowParserMixin.parseExprAtom (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:6811:20)   
    at FlowParserMixin.parseExprSubscripts (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10592:23)
    at FlowParserMixin.parseUpdate (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10577:21)    
    at FlowParserMixin.parseMaybeUnary (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10557:23)    at FlowParserMixin.parseMaybeUnaryOrPrivate (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10411:61)
    at FlowParserMixin.parseExprOps (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10416:23)   


C:\Users\myuser\OneDrive\Рабочий стол\Work\merch-market\frontend>madge --extensions ts,vue --image graph.svg src/

✖ SyntaxError: Unexpected token (7:2)
    at constructor (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:362:19)
    at FlowParserMixin.raise (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:3259:19)
    at FlowParserMixin.unexpected (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:3279:16)      
    at FlowParserMixin.parseExprAtom (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10970:16)  
    at FlowParserMixin.parseExprAtom (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:6811:20)   
    at FlowParserMixin.parseExprSubscripts (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10592:23)
    at FlowParserMixin.parseUpdate (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10577:21)    
    at FlowParserMixin.parseMaybeUnary (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10557:23)    at FlowParserMixin.parseMaybeUnaryOrPrivate (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10411:61)
    at FlowParserMixin.parseExprOps (C:\Users\myuser\AppData\Roaming\npm\node_modules\madge\node_modules\@babel\parser\lib\index.js:10416:23)
```

**Comment by cainrus** [comment]
@Akindin try to add `--ts-config	path/to/your/tsconfig.json`

**Comment by massifrg** [comment]
I have the same problem here, and even with the `--debug` option I can't get the name of the source file that is causing the error.

I'm using `--ts-config`, but I get the same error anyway.
