### ISSUE TITLE
Error with graph generation

### ISSUE THREAD

**Issue by tiborsaas** [pahen/madge#55]
Hi, I just installed it on Windows 7, 64 bit, Using Node 0.10.24
````
F:\dev\www\SnapClip\frontend\api\public\assets\js>madge --image graph.png app.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: This socket is closed.
    at Socket._write (net.js:635:19)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at Socket.Writable.write (_stream_writable.js:180:11)
    at Socket.write (net.js:613:40)
    at Graph.render (C:\Users\Kow\AppData\Roaming\npm\node_modules\madge\node_modules\graphviz\lib\deps\graph.js:380:18)
    at Graph.output (C:\Users\Kow\AppData\Roaming\npm\node_modules\madge\node_modules\graphviz\lib\deps\graph.js:385:8)
    at Object.module.exports.image (C:\Users\Kow\AppData\Roaming\npm\node_modules\madge\lib\graph.js:110:4)
    at Madge.image (C:\Users\Kow\AppData\Roaming\npm\node_modules\madge\lib\madge.js:211:8)
    at run (C:\Users\Kow\AppData\Roaming\npm\node_modules\madge\bin\madge:110:7)
````

Is there some dependency I miss?

**Comment by Baccanno** [comment]
Install GraphViz and put the bin in your PATH

**Comment by neojski** [comment]
The error should be explicit.

I see you're using https://github.com/glejeune/node-graphviz. Most likely we should move this issue there.
