### ISSUE TITLE
"EPIPE" error exporting to graph

### ISSUE THREAD

**Issue by jameswilddev** [pahen/madge#78]
Hello; I'm trying to export a graph of my CoffeeScript/Webpack application to PNG on Windows.  I installed GraphWiz from http://www.graphviz.org/Download_windows.php.  When I run "madge --image dep.png desktop/influx/parser/src" I see:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at Socket._writeGeneric (net.js:675:26)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at Graph.render (C:\Users\james\AppData\Roaming\npm\node_modules\madge\node_modules\graphviz\lib\deps\graph.js:380:18)
    at Graph.output (C:\Users\james\AppData\Roaming\npm\node_modules\madge\node_modules\graphviz\lib\deps\graph.js:385:8)
    at Object.module.exports.image (C:\Users\james\AppData\Roaming\npm\node_modules\madge\lib\graph.js:110:4)

Have I installed the wrong package, or installed it incorrectly?  

Thanks, James.

**Comment by yankouskia** [comment]
Have the same issue

**Comment by MakarovAV** [comment]
The same issue

**Comment by MakarovAV** [comment]
Solved. Problem is: graphviz is not setting PATH variable during install. You should add folder of gvpr.exe (typycally %Graphviz_folder%/bin) to PATH variable.

**Comment by pahen** [comment]
Thanks folks. Added a note about this in the readme now.
